**Task 1**

In [1]:
import pandas 

df = pandas.read_csv("dataset.csv")
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type,quality
0,5.7,0.22,0.20,16.0,0.044,41.0,113.0,0.99862,3.22,0.46,8.9,white,6
1,8.9,0.26,0.33,8.1,0.024,47.0,202.0,0.99558,3.13,0.46,10.8,white,6
2,8.9,0.48,0.53,4.0,0.101,3.0,10.0,0.99586,3.21,0.59,12.1,red,7
3,10.7,0.46,0.39,2.0,0.061,7.0,15.0,0.99810,3.18,0.62,9.5,red,5
4,7.1,0.39,0.79,1.4,0.194,23.0,90.0,0.99212,3.17,0.46,10.5,white,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,5.8,0.26,0.24,9.2,0.044,55.0,152.0,0.99610,3.31,0.38,9.4,white,5
5493,7.4,0.68,0.16,1.8,0.078,12.0,39.0,0.99770,3.50,0.70,9.9,red,6
5494,6.6,0.80,0.03,7.8,0.079,6.0,12.0,0.99630,3.52,0.50,12.2,red,5
5495,5.6,0.54,0.04,1.7,0.049,5.0,13.0,0.99420,3.72,0.58,11.4,red,5
5496,8.7,0.82,0.02,1.2,0.070,36.0,48.0,0.99520,3.20,0.58,9.8,red,5

**Task 2**

In [2]:
df['type'] = df['type'].replace({'white': 1, 'red': 0})
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type,quality
0,5.7,0.22,0.20,16.0,0.044,41.0,113.0,0.99862,3.22,0.46,8.9,1,6
1,8.9,0.26,0.33,8.1,0.024,47.0,202.0,0.99558,3.13,0.46,10.8,1,6
2,8.9,0.48,0.53,4.0,0.101,3.0,10.0,0.99586,3.21,0.59,12.1,0,7
3,10.7,0.46,0.39,2.0,0.061,7.0,15.0,0.99810,3.18,0.62,9.5,0,5
4,7.1,0.39,0.79,1.4,0.194,23.0,90.0,0.99212,3.17,0.46,10.5,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,5.8,0.26,0.24,9.2,0.044,55.0,152.0,0.99610,3.31,0.38,9.4,1,5
5493,7.4,0.68,0.16,1.8,0.078,12.0,39.0,0.99770,3.50,0.70,9.9,0,6
5494,6.6,0.80,0.03,7.8,0.079,6.0,12.0,0.99630,3.52,0.50,12.2,0,5
5495,5.6,0.54,0.04,1.7,0.049,5.0,13.0,0.99420,3.72,0.58,11.4,0,5
5496,8.7,0.82,0.02,1.2,0.070,36.0,48.0,0.99520,3.20,0.58,9.8,0,5

**Task 3**

In [3]:
from sklearn.model_selection import train_test_split

y = df.loc[:,"quality"]
x = df.drop(["quality"], axis=1)
x_train, x_test, y_train, y_test = train_test_split(x,y)

**Task 4**

In [4]:
from sklearn.dummy import DummyRegressor

dummy = DummyRegressor(strategy='mean')
dummy.fit(x_train, y_train)

DummyRegressor()

**Task 5**

In [5]:
training_predictions = dummy.predict(x_train)
test_predictions = dummy.predict(x_test)

**Task 6**

In [6]:
from sklearn.metrics import mean_squared_error

training_error = mean_squared_error(y_train, training_predictions)
print('Dummy regressor training error:' ,training_error)
test_error = mean_squared_error(y_test, test_predictions)
print('Dummy regressor test error:' ,test_error)

Dummy regressor training error: 0.7601754564388764
Dummy regressor test error: 0.7837537923812021

**Task 7**

In [7]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=7)
model.fit(x_train, y_train)

training_predictions = model.predict(x_train)
test_predictions = model.predict(x_test)

training_error = mean_squared_error(y_train, training_predictions)
print('Training error:', training_error)

test_error = mean_squared_error(y_test, test_predictions)
print('Test error:', test_error)

Training error: 0.7297428432799612
Test error: 0.8363636363636363

**Task 8**

In [8]:
import pickle
with open('groupname.pickle', 'wb') as f:
    pickle.dump(model, f)